# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = 'shortcode-caniuse'
license = 'MIT'
licenselink = 'https://github.com/hugo-fixit/shortcode-caniuse/LICENSE'
description = '一个含有 caniuse shortcode 的 Hugo 主题组件。'
min_version = "0.146.0"

# The home page of the theme, where the source can be found
homepage = 'https://github.com/hugo-fixit/shortcode-caniuse'

# If you have a running demo of the theme
demosite = 'https://fixit.lruihao.cn/zh-cn/components/dev-component/'

# Taxonomy terms
tags = ['shortcodes']
features = ['caniuse']

# If the theme has a single author
[author]
name = 'Lruihao'
homepage = 'https://lruihao.cn'
